name: Auto Fork biliup

on:
  schedule:
    - cron: '0 0 * * 1' 
  workflow_dispatch:     

jobs:
  check_and_fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Check for updates and fork if needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Checking for updates..."
        latest_sha=$(curl -s https://api.github.com/repos/biliup/biliup/commits | jq -r '.[0].sha')

        if ! git cat-file -e ${latest_sha}; then
          echo "New updates found, forking repository..."
          curl -X POST \
            -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/biliup/biliup/forks
          echo "Fork completed."
        else
          echo "No new updates found."
        fi
